# Copyright (C) 2026 atinfinity
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math

from nav_msgs.msg import OccupancyGrid

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSDurabilityPolicy, QoSProfile, QoSReliabilityPolicy

from tf2_ros import ConnectivityException, ExtrapolationException, LookupException
from tf2_ros.buffer import Buffer
from tf2_ros.transform_listener import TransformListener

LETHAL_COST = 100


class PeerRobotCostmapPublisher(Node):
    """
    Publish an OccupancyGrid which marks the peer robots as obstacles.

    The poses of the peer robots are taken from TF (the robots share /tf
    and are separated by frame_prefix). Each peer is marked as a filled
    rectangle (footprint_length x footprint_width, rotated by the yaw of
    the peer) on top of a copy of the static map, so that a StaticLayer
    of the costmap can consume it. The static map is
    included because StaticLayer overwrites the master grid, which would
    erase the walls written by the preceding static_layer. The whole
    grid is rebuilt on every cycle, so marks of a moved robot disappear
    automatically. The plain map is published when there is no peer to
    keep the costmap activation unblocked in the single robot setup.
    """

    def __init__(self):
        super().__init__('peer_robot_costmap_publisher')
        self.declare_parameter('peer_base_frames', '')
        self.declare_parameter('footprint_length', 0.032)
        self.declare_parameter('footprint_width', 0.032)
        self.declare_parameter('update_rate', 10.0)

        frames = self.get_parameter('peer_base_frames').value
        self.peer_base_frames = [f.strip() for f in frames.split(',') if f.strip()]
        self.footprint_length = self.get_parameter('footprint_length').value
        self.footprint_width = self.get_parameter('footprint_width').value
        update_rate = self.get_parameter('update_rate').value

        self.map_msg = None
        self.tf_buffer = Buffer()
        self.tf_listener = TransformListener(self.tf_buffer, self)

        latched_qos = QoSProfile(
            depth=1,
            reliability=QoSReliabilityPolicy.RELIABLE,
            durability=QoSDurabilityPolicy.TRANSIENT_LOCAL)
        self.map_sub = self.create_subscription(
            OccupancyGrid, 'map', self.map_callback, latched_qos)
        self.costmap_pub = self.create_publisher(
            OccupancyGrid, 'peer_robots_costmap', latched_qos)
        self.timer = self.create_timer(1.0 / update_rate, self.publish_costmap)

    def map_callback(self, msg):
        self.map_msg = msg

    def publish_costmap(self):
        if self.map_msg is None:
            return

        info = self.map_msg.info
        grid = OccupancyGrid()
        grid.header.frame_id = self.map_msg.header.frame_id
        grid.header.stamp = self.get_clock().now().to_msg()
        grid.info = info
        data = list(self.map_msg.data)

        for frame in self.peer_base_frames:
            try:
                transform = self.tf_buffer.lookup_transform(
                    grid.header.frame_id, frame, rclpy.time.Time())
            except (ConnectivityException, ExtrapolationException,
                    LookupException) as e:
                self.get_logger().warning(
                    f'Failed to lookup transform of {frame}: {e}',
                    throttle_duration_sec=5.0)
                continue
            q = transform.transform.rotation
            yaw = math.atan2(2.0 * (q.w * q.z + q.x * q.y),
                             1.0 - 2.0 * (q.y * q.y + q.z * q.z))
            self.mark_rectangle(
                data, info,
                transform.transform.translation.x,
                transform.transform.translation.y,
                yaw)

        grid.data = data
        self.costmap_pub.publish(grid)

    def mark_rectangle(self, data, info, x, y, yaw):
        # The origin orientation of the map is assumed to be identity,
        # which holds for maps generated by nav2_map_server.
        resolution = info.resolution
        half_length = self.footprint_length / 2.0
        half_width = self.footprint_width / 2.0
        center_mx = (x - info.origin.position.x) / resolution
        center_my = (y - info.origin.position.y) / resolution
        half_diagonal_cells = math.hypot(half_length, half_width) / resolution

        min_mx = max(0, int(math.floor(center_mx - half_diagonal_cells)))
        max_mx = min(info.width - 1,
                     int(math.ceil(center_mx + half_diagonal_cells)))
        min_my = max(0, int(math.floor(center_my - half_diagonal_cells)))
        max_my = min(info.height - 1,
                     int(math.ceil(center_my + half_diagonal_cells)))

        cos_yaw = math.cos(yaw)
        sin_yaw = math.sin(yaw)
        for my in range(min_my, max_my + 1):
            for mx in range(min_mx, max_mx + 1):
                dx = (mx + 0.5 - center_mx) * resolution
                dy = (my + 0.5 - center_my) * resolution
                # Into the footprint frame of the peer
                local_x = cos_yaw * dx + sin_yaw * dy
                local_y = -sin_yaw * dx + cos_yaw * dy
                if abs(local_x) <= half_length and abs(local_y) <= half_width:
                    data[my * info.width + mx] = LETHAL_COST


def main(args=None):
    rclpy.init(args=args)
    node = PeerRobotCostmapPublisher()
    try:
        rclpy.spin(node)
    except (KeyboardInterrupt, rclpy.executors.ExternalShutdownException):
        pass
    finally:
        node.destroy_node()
        rclpy.try_shutdown()


if __name__ == '__main__':
    main()
